name: Python application

on: [push]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World
      run: echo "Hello World from project-backend"

  build:
    needs: hello_world
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run pylint
      run: |
        pylint src/*.py
